version: '0.2'
language: en
files:
  - src/**/*
  - e2e/**/*
  - stories/**/*
ignorePaths:
  - .vscode/**.*
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - .git/**/*
  - .gitignore
  - src/lib/posts/*.md
  - '**/*.svg'
words:
  - aboutads
  - appleboy
  - autorestart
  - bttf
  - Caddyfile
  - CCPA
  - Csvg
  - darkmode
  - EDITMSG
  - elif
  - fastcgi
  - Folkken
  - gsub
  - Hotspots
  - ianvs
  - joshuafolkken
  - joshuastudio
  - Kaku
  - KAWAII
  - Mdsvex
  - mischeck
  - noopener
  - noreferrer
  - opencollective
  - Platformer
  - Platformers
  - Qube
  - redir
  - Shippori
  - sonarcloud
  - sonarjs
  - sonarqube
  - Stylesheet
  - TERE
  - zstd
