version: '0.2'
language: en
files:
  - src/**/*
  - e2e/**/*
  - stories/**/*
ignorePaths:
  - .vscode/**.*
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - .git/**/*
  - .gitignore
words:
  - bttf
  - darkmode
  - EDITMSG
  - elif
  - Folkken
  - Hotspots
  - ianvs
  - joshuafolkken
  - mischeck
  - Qube
  - sonarcloud
  - sonarjs
  - sonarqube
  - Stylesheet
