version: '0.2'
language: en
files:
  - src/**/*
  - e2e/**/*
  - stories/**/*
ignorePaths:
  - .vscode/**.*
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - .git/**/*
  - .gitignore
words:
  - aboutads
  - bttf
  - CCPA
  - darkmode
  - EDITMSG
  - elif
  - Folkken
  - Hotspots
  - ianvs
  - joshuafolkken
  - KAWAII
  - mischeck
  - noopener
  - noreferrer
  - Platformer
  - Platformers
  - Qube
  - sonarcloud
  - sonarjs
  - sonarqube
  - Stylesheet
  - appleboy
  - autorestart
  - Caddyfile
  - zstd
  - redir
  - fastcgi
  - TERE
